# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

has_board = true
target_cpu = "arm64"
board_configuration_label = "//boards/apple-t8122"
bazel_product_bundle_board = "apple-t8122"
board_name = "apple-t8122"
board_description = "Apple Silicon M3"
experimental_apple_support = true
