# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/assembly/bazel_board_configuration.gni")
import("//build/assembly/board_input_bundle.gni")

assert(current_toolchain == default_toolchain && current_cpu == "arm64")

bazel_board_configuration("apple-t8122") {
  testonly = true
  bazel_board_configuration_target = "//boards/apple-t8122"
}

board_input_bundle("framebuffer") {
  drivers = [ {
    package_target = "//src/graphics/display/drivers/boot-framebuffer-display:package"
    package_set = "bootfs"
    driver_components = [ "meta/boot-framebuffer-display.cm" ]
  } ]
  version = build_info_version
}
