# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@fuchsia_build_info//:args.bzl", "build_info_version")
load("@rules_fuchsia//fuchsia:assembly.bzl", "fuchsia_board_configuration", "fuchsia_partitions_configuration", "fuchsia_prebuilt_board_input_bundle")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

fuchsia_partitions_configuration(
    name = "partitions",
    hardware_revision = "apple-t8122-m1n1",
)

fuchsia_board_configuration(
    name = "apple-t8122",
    board_name = "apple-t8122",
    board_input_bundles = [ ":framebuffer" ],
    partitions_configuration = ":partitions",
    provided_features = [ "fuchsia::boot_framebuffer" ],
    version = build_info_version,
)

fuchsia_prebuilt_board_input_bundle(
    name = "framebuffer",
    files = "@gn_targets//boards/apple-t8122:framebuffer",
)
